# Docker Compose Configuration

version: '3.8'

services:
  # Database
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: YourPassword123!
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql

  # Cache
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  # Message Queue
  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin123

  # API Gateway
  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    depends_on:
      - document-service
      - invoice-service
      - payment-service

  # Microservices
  document-service:
    build:
      context: ./backend/document-service
      dockerfile: Dockerfile
    environment:
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=DocumentServiceDB;User Id=sa;Password=YourPassword123!;TrustServerCertificate=true
      - Redis__ConnectionString=redis:6379
    depends_on:
      - sqlserver
      - redis

  invoice-service:
    build:
      context: ./backend/invoice-service
      dockerfile: Dockerfile
    environment:
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=InvoiceServiceDB;User Id=sa;Password=YourPassword123!;TrustServerCertificate=true
      - Redis__ConnectionString=redis:6379
    depends_on:
      - sqlserver
      - redis

  payment-service:
    build:
      context: ./backend/payment-service
      dockerfile: Dockerfile
    environment:
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=PaymentServiceDB;User Id=sa;Password=YourPassword123!;TrustServerCertificate=true
      - Redis__ConnectionString=redis:6379
    depends_on:
      - sqlserver
      - redis

  # Frontend
  frontend:
    build:
      context: ./frontend/client-app
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    depends_on:
      - api-gateway

volumes:
  sqlserver_data:
